export const GET_CATEGORY="GET_CATEGORY"
export const SET_CATEGORY="SET_CATEGORY"
export const GET_VIDEOS="GET_VIDEOS"
export const ADD_TO_WATCHLATER="ADD_TO_WATCHLATER"
export const REMOVE_FROM_WATCHLATER="REMOVE_FROM_WATCHLATER"

